### ISSUE TITLE
Using screwdriver on a ULV Fluid regulator causes serverside crash

### ISSUE THREAD

**Issue by Deepacat** [jmoiron/ulv-covers-modern#1]
Line 7146
[latest.log](https://github.com/jmoiron/ulv-covers-modern/files/15214226/latest.log)

**Comment by jmoiron** [comment]
Just updating to confirm I can reproduce.  First screwdriver use does nothing, second screwdriver crashes with:

```
[00:02:43] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void com.gregtechceu.gtceu.api.gui.widget.NumberInputWidget.setVisible(boolean)'
        at com.jmoiron.ulvcovm.data.covers.FluidRegulatorCoverExt.configureTransferSizeInput(FluidRegulatorCoverExt.java:219) ~[ulvcovm-0.1.jar%23259!/:0.1] {re:classloading}
        at com.jmoiron.ulvcovm.data.covers.FluidRegulatorCoverExt.setTransferMode(FluidRegulatorCoverExt.java:160) ~[ulvcovm-0.1.jar%23259!/:0.1] {re:classloading}
        at com.gregtechceu.gtceu.api.gui.widget.EnumSelectorWidget.setSelected(EnumSelectorWidget.java:119) ~[gtceu-1.20.1-1.2.1.jar%23220!/:?] {re:classloading}
        at com.gregtechceu.gtceu.api.gui.widget.EnumSelectorWidget.<init>(EnumSelectorWidget.java:64) ~[gtceu-1.20.1-1.2.1.jar%23220!/:?] {re:classloading}
        at com.gregtechceu.gtceu.api.gui.widget.EnumSelectorWidget.<init>(EnumSelectorWidget.java:52) ~[gtceu-1.20.1-1.2.1.jar%23220!/:?] {re:classloading}
```

Doesn't happen with the "normal" regulators.  Probably something wrong-sided in there, going to dig around a bit.
